[font]
size = 14.0

[font.bold]
family = "DroidSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DroidSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DroidSansM Nerd Font"
style = "Italic"

[font.normal]
family = "DroidSansM Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"

[colors.primary]
background = '0x282828'
foreground = '0xeeeeee'

[colors.normal]
black = '0x282828'
red = '0xf43753'
green = '0xc9d05c'
yellow = '0xffc24b'
blue = '0xb3deef'
magenta = '0xd3b987'
cyan = '0x73cef4'
white = '0xeeeeee'

[colors.bright]
black = '0x4c4c4c'
red = '0xf43753'
green = '0xc9d05c'
yellow = '0xffc24b'
blue = '0xb3deef'
magenta = '0xd3b987'
cyan = '0x73cef4'
white = '0xfeffff'
