require("ydr.plugins-setup")
require("ydr.plugins.telescope")
require("ydr.plugins.nvim-tree")
require("ydr.plugins.lualine")
require("ydr.plugins.gitsign")
require("ydr.plugins.tree-sitter")

require("ydr.core.options")
require("ydr.core.keymaps")
require("ydr.core.colors")
