require("ydr.plugins-setup")
require("ydr.plugins.telescope")
require("ydr.plugins.nvim-tree")
require("ydr.plugins.lualine")
require("ydr.plugins.gitsign")
require("ydr.plugins.tree-sitter")
require("ydr.plugins.lsp")
require("ydr.plugins.jabs")
require("ydr.plugins.formatter")
require("ydr.plugins.nvim-lint")
require("ydr.plugins.luasnip")

require("ydr.core.options")
require("ydr.core.keymaps")
require("ydr.core.colors")
